# SMTP ?? ?? (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dlrkdals6813@gmail.com
spring.mail.password=xbfb khlk aark onos

# ?? ? ?? ??
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ??? ???? JSON ?? ??
spring.jackson.deserialization.fail-on-unknown-properties=false

# ?? WebFlux ?? ????? ???(ASYNC) ??? MCP ??? ??????
spring.ai.mcp.server.type=ASYNC